#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

info "=== zsh ==="

install_pkg zsh

# oh-my-zsh
OMZ_DIR="$HOME/.oh-my-zsh"
if [[ -d "$OMZ_DIR" ]]; then
  ok "oh-my-zsh already installed"
else
  info "Installing oh-my-zsh..."
  RUNZSH=no CHSH=no sh -c \
    "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

OMZ_CUSTOM="${ZSH_CUSTOM:-$OMZ_DIR/custom}"

# Plugins
clone_if_missing \
  "https://github.com/zsh-users/zsh-autosuggestions" \
  "$OMZ_CUSTOM/plugins/zsh-autosuggestions"

clone_if_missing \
  "https://github.com/zsh-users/zsh-syntax-highlighting" \
  "$OMZ_CUSTOM/plugins/zsh-syntax-highlighting"

clone_if_missing \
  "https://github.com/MichaelAquilina/zsh-you-should-use" \
  "$OMZ_CUSTOM/plugins/you-should-use"

# Powerlevel10k theme
clone_if_missing \
  "https://github.com/romkatv/powerlevel10k" \
  "$OMZ_CUSTOM/themes/powerlevel10k"

# fzf
install_pkg fzf

# fzf shell integration — generates ~/.fzf.zsh referenced in ~/.zsh/fzf.zsh
if [[ ! -f "$HOME/.fzf.zsh" ]]; then
  info "Generating fzf shell integration (~/.fzf.zsh)..."
  _fzf_integration=$(fzf --zsh 2>/dev/null || true)
  if [[ -n "$_fzf_integration" ]]; then
    echo "$_fzf_integration" > "$HOME/.fzf.zsh"
  else
    _keybindings=$(dpkg -L fzf 2>/dev/null | grep 'key-bindings.zsh' | head -1 || true)
    _completion=$(dpkg -L fzf 2>/dev/null | grep 'completion.zsh' | head -1 || true)
    if [[ -n "$_keybindings" ]]; then
      {
        echo "# fzf key bindings and completion (generated by install.sh)"
        [[ -f "$_keybindings" ]] && echo "source '$_keybindings'"
        [[ -f "$_completion"  ]] && echo "source '$_completion'"
      } > "$HOME/.fzf.zsh"
    else
      warn "Could not generate ~/.fzf.zsh automatically."
      warn "After install, run: fzf --zsh > ~/.fzf.zsh"
    fi
  fi
fi

stow_pkg zsh

# Change default shell to zsh
if [[ "$SHELL" != "$(command -v zsh)" ]]; then
  info "Changing default shell to zsh..."
  chsh -s "$(command -v zsh)" || warn "Could not change shell automatically; run: chsh -s $(command -v zsh)"
fi

info "Verifying..."
zsh --version
ok "zsh done"
